[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
  'npm run build:core',
  'npm run build:demo'
]

[start]
cmd = 'npm run start --workspace=packages/demo'
