[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
  'npm run build:core',
  'npm run build --workspace=packages/react',
  'npm run build --workspace=packages/vue',
  'npm run build:demo'
]

[start]
cmd = 'cd packages/demo && npm start'